"""
Transport Agent - Main agent that coordinates transportation planning
Delegates to sub-agents: air_ticket_agent, train_ticket_agent
"""
from states.trip_state import TripState
from orchestration.tracability import log_trace
from agents.air_ticket import air_ticket_agent
from agents.train_ticket import train_ticket_agent
from copy import deepcopy
from typing import List


def transport_agent(state: TripState) -> TripState:
    """
    Main transport agent that coordinates sub-agents for different transport types
    Delegates to air_ticket_agent and train_ticket_agent based on requirements
    """
    destination = state.get("destination", "")
    constraints = state.get("constraints", {}).get("transport", {})
    
    if state.get("log_trace"):
        log_trace(
            state,
            node="transport_agent",
            action="execute",
            reason="Coordinating transportation planning with sub-agents",
            inputs={"constraints": deepcopy(constraints), "destination": destination}
        )
    
    # Determine which sub-agents to call
    # For now, we'll call air_ticket_agent by default for long-distance travel
    # In the future, we can add logic to determine if train is more appropriate
    sub_agents_to_call = _determine_transport_sub_agents(state, constraints)
    
    # Call sub-agents
    for sub_agent_name, sub_agent_func in sub_agents_to_call:
        if state.get("log_trace"):
            log_trace(
                state,
                node="transport_agent",
                action="delegate",
                reason=f"Delegating to {sub_agent_name}",
                inputs={"sub_agent": sub_agent_name}
            )
        
        try:
            state = sub_agent_func(state)
        except Exception as e:
            print(f"Error in {sub_agent_name}: {e}")
            # Continue with other sub-agents even if one fails
    
    # Ensure we have at least some transport options
    transport_options = state.get("transport_options") or _build_default_transport_options(destination, constraints)

    if state.get("log_trace"):
        log_trace(
            state,
            node="transport_agent",
            action="complete recommendations",
            reason="Transport plan generated by sub-agents",
            outputs={"transport_options": deepcopy(transport_options)}
        )

    print(f"transport_agent(): Coordinated {len(sub_agents_to_call)} sub-agents, found {len(transport_options)} transport options")

    return {**state, "transport_options": transport_options}


def _determine_transport_sub_agents(
    state: TripState,
    constraints: dict
) -> List[tuple]:
    """
    Determine which transport sub-agents should be called
    Returns list of (sub_agent_name, sub_agent_function) tuples
    """
    sub_agents = []
    
    # For now, always include air_ticket_agent for long-distance travel
    # In the future, we can add logic to determine:
    # - If destination is close, use train_ticket_agent
    # - If user prefers train, use train_ticket_agent
    # - If budget is very low, consider train_ticket_agent
    # - If there's no train (railway) between origin and destination and only reachable by plane, use air_ticket_agent -> Need to analyze whether there are trains or planes between two places.
    
    # Check if there's a preference for train
    transport_type_preference = constraints.get("preference", {}).get("transport_type")
    
    # Determine which sub-agents to call based on preferences
    if transport_type_preference == "train":
        # User prefers train, only call train agent
        sub_agents.append(("train_ticket_agent", train_ticket_agent))
    elif transport_type_preference == "both":
        # User wants both options
        sub_agents.append(("air_ticket_agent", air_ticket_agent))
        sub_agents.append(("train_ticket_agent", train_ticket_agent))
    else:
        # Default to air travel (for long-distance trips)
        sub_agents.append(("air_ticket_agent", air_ticket_agent))
    
    return sub_agents


def _build_default_transport_options(
    destination: str,
    constraints: dict
) -> list:
    """
    Build a default transport option if sub-agents didn't produce any results
    This is a fallback mechanism
    """
    max_price = None
    preferred_airline = None
    
    if "budget" in constraints and constraints["budget"]:
        max_price = constraints["budget"].get("max_price_per_ticket")
    
    if "preference" in constraints and constraints["preference"]:
        airlines = constraints["preference"].get("airlines")
        if airlines and len(airlines) > 0:
            preferred_airline = airlines[0]
    
    default_option = {
        "type": "flight",
        "to": destination,
        "airline": preferred_airline or "CX",
        "price": max_price if max_price else 500,
        "depart_time": "18:25:00",
        "arrival_time": "22:00:00",
        "reason": "Default option (sub-agents unavailable)"
    }
    
    return [default_option]