"""
Transport Agent - Main agent that coordinates transportation planning
Delegates to sub-agents: air_ticket_agent, train_ticket_agent
"""
from states.trip_state import TripState, default_transport_options
from orchestration.tracability import log_trace
from agents.air_ticket import air_ticket_agent
from agents.train_ticket import train_ticket_agent
from copy import deepcopy
from typing import List


def _has_any_transport_options(transport_options: dict) -> bool:
    flight = transport_options.get("flight") or {}
    return bool(transport_options.get("railway")) or bool(flight.get("outbound")) or bool(flight.get("inbound"))


def transport_agent(state: TripState) -> TripState:
    """
    Main transport agent that coordinates sub-agents for different transport types
    Delegates to air_ticket_agent and train_ticket_agent based on requirements
    """
    destination = state.get("destination", "")
    constraints = state.get("constraints", {}).get("transport", {})

    if state.get("log_trace"):
        log_trace(
            state, node="transport_agent", action="execute",
            reason="Coordinating transportation planning with sub-agents",
            inputs={"constraints": deepcopy(constraints), "destination": destination},
        )

    sub_agents_to_call = _determine_transport_sub_agents(state, constraints)

    for sub_agent_name, sub_agent_func in sub_agents_to_call:
        if state.get("log_trace"):
            log_trace(
                state, node="transport_agent", action="delegate",
                reason=f"Delegating to {sub_agent_name}",
                inputs={"sub_agent": sub_agent_name},
            )
        try:
            state = sub_agent_func(state)
        except Exception as e:
            print(f"Error in {sub_agent_name}: {e}")

    existing = state.get("transport_options")
    transport_options = (
        existing if existing and _has_any_transport_options(existing)
        else _fill_transport_options_with_subagent_errors()
    )

    if state.get("log_trace"):
        log_trace(
            state, node="transport_agent", action="complete recommendations",
            reason="Transport plan generated by sub-agents",
            outputs={"transport_options": deepcopy(transport_options)},
        )

    print(f"transport_agent(): Coordinated {len(sub_agents_to_call)} sub-agents")

    return {**state, "transport_options": transport_options}


def _determine_transport_sub_agents(state: TripState, constraints: dict) -> List[tuple]:
    """Determine which transport sub-agents should be called."""
    sub_agents = []
    transport_type_preference = constraints.get("transport_type")

    if transport_type_preference == "train":
        sub_agents.append(("train_ticket_agent", train_ticket_agent))
    elif transport_type_preference == "both":
        sub_agents.append(("air_ticket_agent", air_ticket_agent))
        sub_agents.append(("train_ticket_agent", train_ticket_agent))
    else:
        sub_agents.append(("air_ticket_agent", air_ticket_agent))

    return sub_agents


def _fill_transport_options_with_subagent_errors() -> dict:
    """Fill transport_options with an error message when all sub-agents failed to produce any results."""
    error_option = {
        "reason": (
            "All transport subagents (flight and railway) got failed at the moment. "
            "Please wait for a few minutes and submit a feedback saying "
            "'Run transport/flight service again'."
        )
    }
    options = default_transport_options()
    options["flight"]["outbound"] = [error_option]
    return options
